allowBuilds:
  '@swc/core': true
  # No longer needs builds:
  better-sqlite3: false
  # Not needed.
  core-js: false
  esbuild: true
  msgpackr-extract: true
  # Not needed.
  protobufjs: false
minimumReleaseAge: 1440
