/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Account: () => import('#controllers/account_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
}
