/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import ActivityBackfillCompleted from '#events/activity_backfill_completed'
import ActivityBackfillStarted from '#events/activity_backfill_started'
import ActivityFeedViewed from '#events/activity_feed_viewed'
import PageViewed from '#events/page_viewed'

export const events = {
  ActivityBackfillCompleted: ActivityBackfillCompleted,
  ActivityBackfillStarted: ActivityBackfillStarted,
  ActivityFeedViewed: ActivityFeedViewed,
  PageViewed: PageViewed,
}
