/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class OauthSessionSchema extends BaseModel {
  static $columns = ['sub', 'updatedAt', 'value'] as const
  $columns = OauthSessionSchema.$columns
  @column({ isPrimary: true })
  declare sub: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class OauthStateSchema extends BaseModel {
  static $columns = ['key', 'updatedAt', 'value'] as const
  $columns = OauthStateSchema.$columns
  @column({ isPrimary: true })
  declare key: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}
