/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fyi.atstore.directory.getListing'

type $nsid = typeof $nsid

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  uri: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'at-uri', maxLength: 2560 }),
  ),
  externalUrl: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ maxLength: 2048 }),
  ),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.payload(
  'application/json',
  /*#__PURE__*/ l.ref<ListingDetailResponse>(
    (() => listingDetailResponse) as any,
  ),
)

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Fetch one public verified listing. Provide exactly one of `uri` (fyi.atstore.listing.detail AT URI) or `externalUrl` (unique storefront URL); `externalUrl` uses the same matching rules as the former resolve endpoint. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output, [
  'ListingNotFound',
  'InvalidParams',
  'AmbiguousResolution',
])

export { main }

const $lxm = $nsid

type $lxm = typeof $lxm

export { $lxm }

type ListingCardGet = {
  $type?: 'fyi.atstore.directory.getListing#listingCardGet'

  /**
   * AT URI of the fyi.atstore.listing.detail record.
   */
  uri: l.AtUriString
  name: string
  accent: 'blue' | 'pink' | 'purple' | 'green' | l.UnknownString
  rating: string | null
  appTags: string[]
  iconUrl: string | null
  tagline: string
  category: string
  priceLabel: string
  description: string
  reviewCount: number
  categorySlug: string | null
  heroImageUrl: string | null
  categorySlugs: string[]
  productAccountHandle: string | null
}

export type { ListingCardGet }

const listingCardGet = /*#__PURE__*/ l.typedObject<ListingCardGet>(
  $nsid,
  'listingCardGet',
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.string({ format: 'at-uri', maxLength: 2560 }),
    name: /*#__PURE__*/ l.string({ maxLength: 640 }),
    accent: /*#__PURE__*/ l.string<{
      maxLength: 16
      knownValues: ['blue', 'pink', 'purple', 'green']
    }>({ maxLength: 16 }),
    rating: /*#__PURE__*/ l.nullable(/*#__PURE__*/ l.string({ maxLength: 16 })),
    appTags: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxLength: 256 })),
    iconUrl: /*#__PURE__*/ l.nullable(
      /*#__PURE__*/ l.string({ maxLength: 8192 }),
    ),
    tagline: /*#__PURE__*/ l.string({ maxLength: 2000 }),
    category: /*#__PURE__*/ l.string({ maxLength: 640 }),
    priceLabel: /*#__PURE__*/ l.string({ maxLength: 32 }),
    description: /*#__PURE__*/ l.string({ maxLength: 20000 }),
    reviewCount: /*#__PURE__*/ l.integer(),
    categorySlug: /*#__PURE__*/ l.nullable(
      /*#__PURE__*/ l.string({ maxLength: 512 }),
    ),
    heroImageUrl: /*#__PURE__*/ l.nullable(
      /*#__PURE__*/ l.string({ maxLength: 8192 }),
    ),
    categorySlugs: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.string({ maxLength: 512 }),
    ),
    productAccountHandle: /*#__PURE__*/ l.nullable(
      /*#__PURE__*/ l.string({ maxLength: 512 }),
    ),
  }),
)

export { listingCardGet }

type ListingLinkRow = {
  $type?: 'fyi.atstore.directory.getListing#listingLinkRow'
  uri: string
  label?: string
}

export type { ListingLinkRow }

const listingLinkRow = /*#__PURE__*/ l.typedObject<ListingLinkRow>(
  $nsid,
  'listingLinkRow',
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.string({ maxLength: 2048 }),
    label: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 640 })),
  }),
)

export { listingLinkRow }

type ListingDetailResponse = {
  $type?: 'fyi.atstore.directory.getListing#listingDetailResponse'
  links?: ListingLinkRow[]
  listing: ListingCardGet
  repoDid: string | null
  createdAt: string | null
  sourceUrl: string | null
  updatedAt: string | null
  externalUrl: string | null
  screenshots?: string[]
  sourceTagline: string | null
  isStoreManaged: boolean
  productAccountDid: string | null
  sourceFullDescription: string | null
}

export type { ListingDetailResponse }

const listingDetailResponse =
  /*#__PURE__*/ l.typedObject<ListingDetailResponse>(
    $nsid,
    'listingDetailResponse',
    /*#__PURE__*/ l.object({
      links: /*#__PURE__*/ l.optional(
        /*#__PURE__*/ l.array(
          /*#__PURE__*/ l.ref<ListingLinkRow>((() => listingLinkRow) as any),
        ),
      ),
      listing: /*#__PURE__*/ l.ref<ListingCardGet>(
        (() => listingCardGet) as any,
      ),
      repoDid: /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxLength: 2048 }),
      ),
      createdAt: /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxLength: 64 }),
      ),
      sourceUrl: /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxLength: 8192 }),
      ),
      updatedAt: /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxLength: 64 }),
      ),
      externalUrl: /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxLength: 2048 }),
      ),
      screenshots: /*#__PURE__*/ l.optional(
        /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxLength: 4096 })),
      ),
      sourceTagline: /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxLength: 20000 }),
      ),
      isStoreManaged: /*#__PURE__*/ l.boolean(),
      productAccountDid: /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxLength: 2048 }),
      ),
      sourceFullDescription: /*#__PURE__*/ l.nullable(
        /*#__PURE__*/ l.string({ maxLength: 20000 }),
      ),
    }),
  )

export { listingDetailResponse }
