/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.blocks.imageGallery'

type $nsid = typeof $nsid

export { $nsid }

type Main = {
  $type?: 'pub.leaflet.blocks.imageGallery'

  /**
   * Gap between images in pixels.
   */
  gap?: number
  format?: 'grid' | 'carousel' | 'strip' | l.UnknownString
  images: Image[]

  /**
   * Max width per image in grid view (px); drives how many columns fit.
   */
  maxWidth?: number
}

export type { Main }

const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    gap: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    format: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{ knownValues: ['grid', 'carousel', 'strip'] }>(),
    ),
    images: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<Image>((() => image) as any),
    ),
    maxWidth: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Image = {
  $type?: 'pub.leaflet.blocks.imageGallery#image'

  /**
   * Alt text description of the image, for accessibility.
   */
  alt?: string
  image: l.BlobRef
  aspectRatio: AspectRatio
}

export type { Image }

const image = /*#__PURE__*/ l.typedObject<Image>(
  $nsid,
  'image',
  /*#__PURE__*/ l.object({
    alt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    image: /*#__PURE__*/ l.blob({ accept: ['image/*'], maxSize: 1000000 }),
    aspectRatio: /*#__PURE__*/ l.ref<AspectRatio>((() => aspectRatio) as any),
  }),
)

export { image }

type AspectRatio = {
  $type?: 'pub.leaflet.blocks.imageGallery#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

const aspectRatio = /*#__PURE__*/ l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  /*#__PURE__*/ l.object({
    width: /*#__PURE__*/ l.integer(),
    height: /*#__PURE__*/ l.integer(),
  }),
)

export { aspectRatio }
