name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    if: github.repository == 'eurosky-social/eurosky-portal'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          check-latest: true
          cache: pnpm

      - name: Create pull request for next release, or Publish a new github release and tag
        id: changesets
        uses: changesets/action@v1

        with:
          title: Prepare next release
          createGithubReleases: true
          publish: pnpm release
          version: pnpm version-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print changeset output
        run: echo '${{ toJson(steps.changesets.outputs) }}''

      - name: Publish release
        if: steps.changesets.outputs.published == 'true'
        uses: ./.github/workflows/publish.yaml
        with:
          tag_ref: 'refs/tags/v${{steps.changesets.outputs.publishedPackages[0].version}}'
